# fly.toml app configuration file generated for fullstackopen-part11-pokedex on 2024-03-02T19:37:46+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'fullstackopen-part11-pokedex'
primary_region = 'arn'

[build]

[env]
  PORT = "3000"

[processes]
  app = "node app.js"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[http_service.checks]
  grace_period = "10s"
  interval = "30s"
  method = "GET"
  timeout = "5s"
  path = "/health"  

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1

[deploy]
  strategy = "bluegreen"
