name: Health Check

on:
  schedule:
    - cron: '0 0 * * 0'
  push:
    branches:
      - main
      - dev

jobs:
  health_check:
    runs-on: ubuntu-20.04
    steps:
      - uses: jtalk/url-health-check-action@v4
        with:
          url: https://fullstackopen-part11-pokedex.fly.dev/health
          max-attempts: 3